### ISSUE TITLE
Get Account Activity

### ISSUE THREAD

**Issue by DanielFCampos** [VermeirJellen/PoloniexR#2]
Hi!

First of all, I would like to congratulate and thank you for this awesome piece of work (a real masterpiece).

I am pretty new to the project and to package itself but I haven't had any "unsolvable through google" kind of problem. Today it was different and this is why I came here to kindly ask your help.

I have used my key/secret pair successfully for other requests, however, for "returnDepositWithdrawals" it throws an error. See below my piece of code (pretty much the same one from GitHub):

account.activity <- ProcessTradingRequest(poloniex.trading,
                                          command = poloniex.trading@commands$returnDepositWithdrawals,
                                          args = list(start = as.numeric(as.POSIXct("2017-01-01 00:00:00 UTC")),
                                          end   = as.numeric(as.POSIXct("2018-01-01 00:00:00 UTC"))))

The error thrown is as follows:

Error in ProcessTradingRequest(poloniex.trading, command = poloniex.trading@commands$returnDepositWithdrawals,  : 
  Poloniex returned "Invalid command." response error while processing parameters "command=returnDepositWithdrawals&nonce=15044158345873&start=1483236000&end=1514772000"

Do you have any idea of what I may be facing?

Thank you so much!

Best,
Daniel Campos

**Comment by VermeirJellen** [comment]
Hey Daniel,

Thanks for your interest in this project.
There was indeed a bug related to the command name value of the `returnDepositWithdrawals` field. I have created a note in the readme file to explain the issue to the users:

> Note - version 0.0.1 contains a small bug related to the returnDepositWithdrawals trading command. The associated value of this field should be returnDepositsWithdrawals (instead of the default returnDepositWithdrawals value). Starting from version 0.0.2 both the command name field and corresponding value have been changed to returnDepositsWithdrawals in order to correctly represent the Poloniex command string and value. At the time of writing, the latest version has not yet been uploaded to CRAN (view issues). If you are using version 0.0.1 you can manually modify the command field to the correct value, as explained in the tutorial below

You have two options:
- Install the latest version from Github (and use the updated `returnDepositsWithdrawals` command field) or
- Keep using the CRAN version and update the value of the old `returnDepositWithdrawals` field as follows:

```
commands.new <- list(returnDepositWithdrawals = "returnDepositsWithdrawals")
poloniex.trading <- SetPoloniexTradingCommands(poloniex.trading,
                                               commands = commands.new)
```

This will give a warning because all the other command field values are kept to their default values (which is ok). You can now execute the trading request and it should behave correctly:

```
account.activity <- ProcessTradingRequest(poloniex.trading,
                                          command = poloniex.trading@commands$returnDepositWithdrawals,
                                          args  = list(start = as.numeric(as.POSIXct("2017-01-01 00:00:00 UTC")),
                                                       end   = as.numeric(as.POSIXct("2018-01-01 00:00:00 UTC"))))`
```

I will request an update on CRAN with the fix once I get some more feedback on the package. There might be some other issues that require fixing.

Thanks for letting me know!

**Comment by DanielFCampos** [comment]
Great! Thank you for your prompt reply!

With your suggestion, I got this fixed. Thank you SO much!

Again, great job you've done.
